In [148]:
import torch
import numpy as np
from itertools import product, chain
from functools import reduce

In [149]:
def string_matmul(list_1, list_2):
    prod = [element[0] + element[1] for element in product(list_1, list_2)]
    return prod

In [173]:
test = [torch.tensor([(0,1,2),(3,4,5)], dtype=torch.float32),torch.tensor([(0,1,2),(0,1,2)], dtype=torch.float32),torch.tensor([(0,1,2),(0,1,2)], dtype=torch.float32)]

In [191]:
test[0].view(1, -1)

tensor([[0., 1., 2., 3., 4., 5.]])

In [193]:
result = test[0][:, :, None] @ test[1][:, None, :]
result

tensor([[[ 0.,  0.,  0.],
         [ 0.,  1.,  2.],
         [ 0.,  2.,  4.]],

        [[ 0.,  3.,  6.],
         [ 0.,  4.,  8.],
         [ 0.,  5., 10.]]])

In [196]:
result[1, :, 0]

tensor([0., 0., 0.])

In [197]:
result[1, 0, :]

tensor([0., 3., 6.])

In [198]:
result.view(2, -1)

tensor([[ 0.,  0.,  0.,  0.,  1.,  2.,  0.,  2.,  4.],
        [ 0.,  3.,  6.,  0.,  4.,  8.,  0.,  5., 10.]])

In [185]:
reduce((lambda x, y: (x[:, :, None] @ y[:, None, :]).view(2, -1)), test).shape

torch.Size([2, 27])

In [151]:
output, samples, order = len(test), test[0].shape[0], test[0].shape[1]

In [155]:
all_samples = [[test[i][j,:] for i in np.arange(output)] for j in np.arange(samples)]

In [171]:
proc_samples = torch.tensor([reduce((lambda x, y: string_matmul(x, y)), all_samples[j]) for j in np.arange(samples)])

In [172]:
proc_samples.shape

torch.Size([2, 27])

In [159]:
torch.cat(proc_sample_one)

TypeError: expected Tensor as element 0 in argument 0, but got list

In [137]:
torch.cat([x for x in proc_sample_one], dim=0)

TypeError: expected Tensor as element 0 in argument 0, but got list

In [85]:
dummy = torch.Tensor(output, samples, order)
dummy.shape
torch.cat(test, out=dummy).shape

torch.Size([6, 3])

In [34]:
element=1
temp = string_matmul(test[element][0,:],test[0][element,:])

In [49]:
uv_list = torch.cat([x for x in test], dim=1)

In [58]:
torch.cat(test)

tensor([[0., 1., 2.],
        [0., 1., 2.],
        [0., 1., 2.],
        [0., 1., 2.],
        [0., 1., 2.],
        [0., 1., 2.]], grad_fn=<CatBackward>)

In [17]:
[string_matmul(test[element][0,:],test[0][element,:]) for element in test[0]]

TypeError: only integer tensors of a single element can be converted to an index